Try clang.

diff --git a/.github/workflows/others.yml b/.github/workflows/others.yml
--- a/.github/workflows/others.yml
+++ b/.github/workflows/others.yml
@@ -19,14 +19,8 @@ jobs:
           sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
       - name: Build X86_64
         run: |
-          which gcc
-          gcc -v
-          echo $PATH
-          ln -s /usr/local/bin/gcc-14 /usr/local/bin/gcc
-          which gcc
-          export CC=/usr/local/bin/gcc-14
           PATH='/usr/local/opt/bison/bin:'$PATH
-          ./compile_macos_gcc.sh || true # Will fail to install
+          ./compile_macos_clang.sh || true # Will fail to install
           if [ ! -f release/src/ngspice ]; then false; fi
       - name: Install X86_64
         run: |
